spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Project
    username: victormartins
    password: badPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mustache:
    servlet:
      cache: false
  profiles:
    active: dev
server:
  port: 8710