### Add an User
POST http://localhost:8710/rest/users/new
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword"
}
### Get All Users
GET http://localhost:8710/rest/users

### Update Userdetails
PUT http://localhost:8710/rest/users/1273c390-17e9-4504-ac9c-1166c4ebea7b/d
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword",
  "firstName" : "Victor",
  "lastName" : "Fernandes Martins",
  "birthdate" : "1987-10-13"
}

### Get UserDetails by an ID
GET http://localhost:8710/rest/users/75224d8b-e47f-47d8-979b-7ef4a2d61296/d

### Add new TodoList
POST http://localhost:8710/rest/todolist/new
Content-Type: Application/json

{
  "creatonDate": "",
  "todoListName": "firstTodoList",
  "user": {
    "userID": "76e3d6e8-886a-4db4-943a-2518b491debb",
    "email" : "VictorMartins@mail.de",
    "password" : "badPassword"
  }
}