### Add an User
POST http://localhost:8710/rest/users/new
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword"
}
### Get All Users
GET http://localhost:8710/rest/users

### Update Userdetails
PUT http://localhost:8710/rest/users/791c5d1a-fb38-44f8-8cc8-ea6acaab5c2f/d
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword",
  "firstName" : "Victor",
  "lastName" : "Fernandes Martins",
  "birthDate" : "1987-10-13"
}

### Get UserDetails by an ID
GET http://localhost:8710/rest/users/791c5d1a-fb38-44f8-8cc8-ea6acaab5c2f/d

### Add new TodoList
POST http://localhost:8710/rest/todolist/791c5d1a-fb38-44f8-8cc8-ea6acaab5c2f/new
Content-Type: Application/json

{
  "todoListName": "firstTodoList"
}

### Get TODOLIST by ID
GET http://localhost:8710/rest/todolist/791c5d1a-fb38-44f8-8cc8-ea6acaab5c2f

### Get All ShoppingLists by User
GET http://localhost:8710/rest/todolist/shoppinglist/users/791c5d1a-fb38-44f8-8cc8-ea6acaab5c2f


### Add new ShoppingList
POST http://localhost:8710/rest/todolist/shoppinglist/791c5d1a-fb38-44f8-8cc8-ea6acaab5c2f/new
Content-Type: Application/json

{
  "marketName": "mini Mercado"
}

### Add Products to ShoppingList
POST http://localhost:8710/rest/todolist/shoppinglist/8/products/new
Content-Type: Application/json

{
  "name": "Coca Cola",
  "brand": "Coca Cola Comp",
  "price": 1.23,
  "qty": 4,
  "type": "Drink"
}