### Add new ShoppingList
POST http://localhost:8710/rest/todolist/shoppinglist/user/d054877e-2f6d-4d0b-b32a-62123d16dc7e/new
Content-Type: Application/json

{
  "todoListName": "ShoppingList Penny",
  "marketName": "Penny"
}
### Add new ShoppingList with Market ALDI
POST http://localhost:8710/rest/todolist/shoppinglist/user/d054877e-2f6d-4d0b-b32a-62123d16dc7e/new
Content-Type: Application/json

{
  "todoListName": "ShoppingList ALDI",
  "marketName": "ALDI"
}

### Add Products to ShoppingList
POST http://localhost:8710/rest/todolist/shoppinglist/1/products/new
Content-Type: Application/json

{
  "name": "Coca Cola",
  "brand": "Coca Cola Comp",
  "price": 1.23,
  "qty": 4,
  "type": "Drink"
}

### Show All Products of determinate Shopping List
GET http://localhost:8710/rest/todolist/shoppinglist/1