### Add new ShoppingList
POST http://localhost:8710/rest/todolist/shoppinglist/a47888b7-6f2b-483e-bf67-e6a3248345f7/new
Content-Type: Application/json

{
  "marketName": "mini Mercado"
}

### Add Products to ShoppingList
POST http://localhost:8710/rest/todolist/shoppinglist//products/new
Content-Type: Application/json

{
  "name": "Coca Cola",
  "brand": "Coca Cola Comp",
  "price": 1.23,
  "qty": 4,
  "type": "Drink"
}