### Get TODOLIST by ID
GET http://localhost:8710/rest/todolist/482e883d-dbfe-46cf-b5f9-51fe9b632275

### Get All ShoppingLists by User
GET http://localhost:8710/rest/todolist/shoppinglist/user/482e883d-dbfe-46cf-b5f9-51fe9b632275

### Get All TaskLists by User
GET http://localhost:8710/rest/todolist/tasklist/user/d054877e-2f6d-4d0b-b32a-62123d16dc7e
