### Get TODOLIST by ID
GET http://localhost:8710/todolist/{{UserID}}
Authorization: Bearer {{Token}}

### Get All ShoppingLists by User
GET http://localhost:8710/todolist/shoppinglist/user/{{UserID}}
Authorization: Bearer {{Token}}

### Get All TaskLists by User
GET http://localhost:8710/todolist/tasklist/user/{{UserID}}
Authorization: Bearer {{Token}}