### Add an User
POST http://localhost:8710/rest/users/new
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword"
}
### Add an User
POST http://localhost:8710/rest/users/new
Content-Type: Application/json

{
  "password" : "badPassword"
}
### Get All Users
GET http://localhost:8710/rest/users

### Update Userdetails
PUT http://localhost:8710/rest/users/d054877e-2f6d-4d0b-b32a-62123d16dc7e/d
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword",
  "firstName" : "Victor",
  "lastName" : "Fernandes Martins",
  "birthDate" : "1990-10-13"
}

### Get UserDetails by an ID
GET http://localhost:8710/rest/users/a47888b7-6f2b-483e-bf67-e6a3248345f7/d

