## Login
POST http://localhost:8710/login
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword"
}
###
GET http://localhost:8710/users/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWaWN0b3JNYXJ0aW5zQG1haWwuZGUiLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODcxMC9sb2dpbiIsImV4cCI6MTY5MzA4Nzk4M30.haaqp-Jr7JQHpqWC5K3ZuhVAqhK97DQU3i1jwslZy3E


### Add an User
POST http://localhost:8710/users
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword"
}
### Get All Users
GET http://localhost:8710/users

### Update Userdetails
PATCH http://localhost:8710/users/482e883d-dbfe-46cf-b5f9-51fe9b632275/d
Content-Type: Application/json

{
  "email" : "VictorMartins@mail.de",
  "password" : "badPassword",
  "firstName" : "Victor",
  "lastName" : "Fernandes Martins",
  "birthDate" : "1990-10-13"
}

### Get UserDetails by an ID
GET http://localhost:8710/users/a47888b7-6f2b-483e-bf67-e6a3248345f7/d

