
### Add new ShoppingList with SuperMarket ALDI
POST http://localhost:8710/todolist/shoppinglist
Content-Type: Application/json
Authorization: Bearer {{Token}}

{
  "todoListName": "ShoppingList ALDI",
  "marketName": "ALDI"
}


### Get ALDI Shopping List
GET http://localhost:8710/todolist/shoppinglist
Authorization: Bearer {{Token}}

### Get Penny Shopping List
GET http://localhost:8710/todolist/shoppinglist/2
Authorization: Bearer {{Token}}
### Get Penny Shopping List

GET http://localhost:8710/todolist/shoppinglist/2/products
Authorization: Bearer {{Token}}


### Get Penny Shopping List
GET http://localhost:8710/todolist/shoppinglist/3
Authorization: Bearer {{Token}}


### Get Penny Shopping List
GET http://localhost:8710/todolist/shoppinglist/4
Authorization: Bearer {{Token}}

### Delete Shoping List
DELETE http://localhost:8710/todolist/shoppinglist/3
Authorization: Bearer {{Token}}