
### Add new ShoppingList with SuperMarket ALDI
POST http://localhost:8710/todolist/shoppinglist
Content-Type: Application/json
Authorization: Bearer {{Token}}

{
  "todoListName": "ShoppingList ALDI",
  "marketName": "ALDI"
}

### Get All Shopping List
GET http://localhost:8710/todolist/shoppinglist
Authorization: Bearer {{Token}}

### Get Products of ALDI
GET http://localhost:8710/todolist/shoppinglist/2
Authorization: Bearer {{Token}}

### Add Product to ALDI
POST http://localhost:8710/todolist/shoppinglist/2/products
Content-Type: Application/json
Authorization: Bearer {{Token}}

{
  "name": "Coca Cola",
  "brand": "Coca Cola Comp",
  "price": 1.23,
  "qty": 4,
  "type": "Drink"
}

### Delete Shoping List
DELETE http://localhost:8710/todolist/shoppinglist/3
Authorization: Bearer {{Token}}