### Get All TODOLIST (Logged In)
GET http://localhost:8710/todolist
Authorization: Bearer {{Token}}

### Get All ShoppingLists (Logged In)
GET http://localhost:8710/todolist/shoppinglist
Authorization: Bearer {{Token}}

### Get All TaskLists (Logged In)
GET http://localhost:8710/todolist/tasklist
Authorization: Bearer {{Token}}