### Get All TODOLIST
GET http://localhost:8710/todolist
Authorization: Bearer {{Token}}

### Get All ShoppingLists by User
GET http://localhost:8710/todolist/shoppinglist
Authorization: Bearer {{Token}}

### Get All TaskLists by User
GET http://localhost:8710/todolist/tasklist
Authorization: Bearer {{Token}}