### Who I am?
GET http://localhost:8710/users/me
Authorization: Bearer {{Token}}


### Add an User
POST http://localhost:8710/users/register
Content-Type: Application/json
Authorization: Bearer {{Token}}

{
  "email" : "Stupid@mail.de",
  "password" : "Victor"
}
### Update Userdetails
PATCH http://localhost:8710/users/{{UserID}}
Content-Type: Application/json
Authorization: Bearer {{Token}}

{
  "email" : "VictorMartins@mail.de",
  "firstName" : "Victor",
  "lastName" : "Fernandes Martins",
  "birthDate": "1987-10-13"
}

### Get UserDetails by an ID
GET http://localhost:8710/users/{{UserID}}
Authorization: Bearer {{Token}}
